import asyncio
import sys
from openai import (
    OpenAI, 
    NotFoundError
)
from telegram import (
    Update, 
    ReplyKeyboardMarkup 
)
from telegram.ext import (
    ContextTypes,
    CallbackContext
) 

from config import BOT_CONSTANTS as BC
from document_driver_base import DocumentDriverBase
from utils import (SharedUtils, 
                   DocumentExport
)

# Initialize OpenAI client
OPENAI_CLIENT = OpenAI(api_key=BC.OPENAI_API_KEY)

class LectureDriver(DocumentDriverBase):
    def __init__(self):
        self.text = ""
        self.instruction_text = ""
        self.language = ""
        self.oai_docgen_thread = None
        self.oai_docgen_thread_id = None
        self.main_chapters = []
        self.sub_chapters = []
        self.chapter_titles = {}
        self.all_chapter_titles = ""
        self.tg_thread_id = None
        self.process_complete = False
        self.process_status = "generate main chapters"
                
        
        try:
            self.openai = OPENAI_CLIENT
            self.assistant = OPENAI_CLIENT.beta.assistants.retrieve(BC.OPENAI_ASSISTANT_ID)
        except NotFoundError as e:
            print(f"Assistant not found error? {e}")
            print(f"bot server terminated - the assistant id is probably wrong")
            sys.exit()
            
            
        # echo_handler = MessageHandler(
        # filters.TEXT & (~filters.COMMAND), 
        # lambda update, context: self.echo(update, context),
        # )
        
        # self.application.add_handler(echo_handler)


    async def echo(self, update: Update, context: ContextTypes.DEFAULT_TYPE):
        tg_thread_id = update.effective_chat.id
        print(f'tg_thread_id: {tg_thread_id}') if BC.VERBOSE else None

            
    async def generate_main_chapters(self, update: Update, context: CallbackContext):
        self.process_status = "generate main chapters"
        self.main_chapters = ""
        self.tg_thread_id = update.effective_chat.id
        print(f"scaffold self.tg_thread_id {self.tg_thread_id}") if BC.VERBOSE else None

        self.instruction_text = update.message.text
        
        try:
            self.oai_docgen_thread = OPENAI_CLIENT.beta.threads.create()
            self.oai_docgen_thread_id = self.oai_docgen_thread.id
            
            # set language - ideally this would be either set by the Telegram user
            # and/or by using the telegram application to check his locale setting.
            self.language = await SharedUtils.identify_language(self.instruction_text)

            # Create Parent-Chapters
            prompt = f"""
                Your Role: Functioning as a generative artificial intelligence, your expertise lies in crafting the scaffold or structure of a lecture.
                Knowledge: Your task involves utilizing your general knowledge, intentionally without any attached documents. Please refrain from expressing dissatisfaction with this arrangement.
                Your Task: Generate a lecture structure with chapter titles based on the User-Input provided.
                Response Content: Your response must consist of minimum 1 chapter and never exceed 3 chapters. Enumerate each chapter incrementally starting from 1, with a line-feed character at the end of each line. Do not comment. Do never address the user. Do not write an introduction. Limit your answer to the chapter-titles only.
                Language: Generate your response in the {self.language} language.
                Social Responsibility: Avoid suggesting politically controversial chapters or those infringing on individual privacy, unless the subject is of public interest, and the suggested chapter or sub-chapter is already part of the public domain.
                The Purpose of This Task: The scaffold, or list of chapters, generated by you will serve as the foundation for iteratively generating sub-chapters in a subsequent process.
                Create the structure based on the following user-input: {self.instruction_text}
            """
            print(f"\n\nprompt:\n{prompt}\n\n") if BC.VERBOSE else None
            # create prompt
            message = OPENAI_CLIENT.beta.threads.messages.create(
                thread_id=self.oai_docgen_thread_id,
                role="user",
                content=prompt
            )
            
            # run prompt
            run = OPENAI_CLIENT.beta.threads.runs.create(
            thread_id=self.oai_docgen_thread_id,
            assistant_id=self.assistant.id,
            instructions=BC.OPENAI_INSTRUCTIONS
            )
            
            # wait async for response for OpenAI and check status every 5 seconds
            tg_main_chapters = "scaffolding document structure... \n\n"
            await context.bot.send_message(chat_id=self.tg_thread_id, text=tg_main_chapters)
            
            while True:
                await context.bot.send_chat_action(chat_id=self.tg_thread_id, action='typing')
                run = OPENAI_CLIENT.beta.threads.runs.retrieve(
                    thread_id = self.oai_docgen_thread_id,
                    run_id = run.id
                )
                print(run.status) if BC.VERBOSE else None
                if run.status == "completed":
                    break
                await asyncio.sleep(5)
                
            # once "completed", get messages (response from OpenAI)
            messages = OPENAI_CLIENT.beta.threads.messages.list(
                thread_id=self.oai_docgen_thread_id
            )
            print(f"structure message: {messages}") if BC.VERBOSE else None

            # pick clean response
            last_message = messages.data[0]
            oai_response = last_message.content[0].text.value
            oai_response = SharedUtils.remove_reference(oai_response=oai_response)
            
            print(f"\n\nscaffolding main structure... \n\n {oai_response}\n\n\n") if BC.VERBOSE else None
            
            # update telegram with the main chapters:
            # tg_main_chapters = "scaffolding main structure... \n\n" + oai_response
            # await context.bot.send_message(chat_id=self.tg_thread_id, text=tg_main_chapters)

            
            # Split the text into a list of sub-strings
            self.text = oai_response.split('\n')
        except Exception as e:
            print(f"Error while scaffolding main chapters: {e}\nExit to chat mode.\n")
            return False
            
        return True

        
    async def generate_sub_chapters(self, update: Update, context: CallbackContext):
        self.process_status = "generate sub chapters"
        self.sub_chapters = ""
        all_main_chapters = '\n'.join(line for line in self.text)
        try:
            # iterate through lines and create sub-chapters.
            for line in self.text:
                # tg_message = f"scuffolding sub structure for '{line}'"
                # await context.bot.send_message(chat_id=self.tg_thread_id, text=tg_message)
                if line.strip() == '':
                    continue
                line = line.lstrip()
                print(line) if BC.VERBOSE else None
                
                prompt = f"""
                    Your Role: You function as a generative artificial intelligence, specializing in the creation of academic essays and lectures.
                    Your Task: Generate a minimum of 1 and a maximum of 2 sub-chapter titles for the current parent-chapter title provided ({line}). Refer to the overview of all parent-chapter titles ({all_main_chapters}) for context.
                    Enumeration: Each sub-chapter title is enumerated with a prefix representing the parent-chapter title number, followed by a dot separator, and an incrementally enumerated suffix starting from 1 followe by a space character.
                    Format: The format requires each line to commence with the sub-chapter number, followed by the sub-chapter title text and a line-feed at the end.
                    Knowledge Source: Utilize your general knowledge acquired during training.
                    Language: Present your response in the {self.language} language.
                    Social Responsibility: When addressing topics within the public domain, such as public figures or organizations, provide a comprehensive response based on accessible data from your training.
                    Style: Tailor your expressions and language style to suit the audience, composed of high-profile scholars and academics.
                    User Instructions: Follow the provided {self.instruction_text}.            
                """
                message = OPENAI_CLIENT.beta.threads.messages.create(
                    thread_id=self.oai_docgen_thread_id,
                    role="user",
                    content=prompt
                )
                
                run = OPENAI_CLIENT.beta.threads.runs.create(
                thread_id=self.oai_docgen_thread_id,
                assistant_id=self.assistant.id,
                instructions=BC.OPENAI_INSTRUCTIONS
                )
                
                while True:
                    await context.bot.send_chat_action(chat_id=self.tg_thread_id, action='typing')
                    run = OPENAI_CLIENT.beta.threads.runs.retrieve(
                        thread_id = self.oai_docgen_thread_id,
                        run_id = run.id
                    )
                    print(run.status) if BC.VERBOSE else None
                    if run.status == "completed":
                        break
                    await asyncio.sleep(5)
                
                messages = OPENAI_CLIENT.beta.threads.messages.list(
                    thread_id=self.oai_docgen_thread_id
                )
                # pick correct message
                last_message = messages.data[0]
                oai_response = last_message.content[0].text.value
                oai_response = SharedUtils.remove_reference(oai_response=oai_response)
                print(f"\n\n {line}\n") if BC.VERBOSE else None
                print(f"{oai_response}\n\n\n") if BC.VERBOSE else None
                # sometimes the AI generates content including a leading sub-chapter title
                # we don't want that as we add the sub-chapter title programmatically
                if oai_response.startswith(line):
                    # Replace the sub-title with an empty string
                    oai_response = oai_response[len(line):]
                # we create a list containing all the sub-chapter-title strings
                self.chapter_titles[line] = [line.strip() for line in oai_response.splitlines()]
                # tg_subchapters = "\n" + oai_response + "\n\n"
                # await context.bot.send_message(chat_id=self.tg_thread_id, text=tg_subchapters)

            # produce string with all chapters sequentually listed for AI reference
            self.all_chapter_titles = ""
            for parent_chapter, sub_chapter_list in self.chapter_titles.items():
                self.all_chapter_titles += parent_chapter.strip() + "\n"
                for sub_chapter in sub_chapter_list:
                    self.all_chapter_titles += sub_chapter.strip() + "\n"
                
            print(f"The complete scaffold: \n {self.all_chapter_titles}") if BC.VERBOSE else None
            tg_chapter_overview = "\n<b><u>Suggested document structure:</u></b>\n\n" + self.all_chapter_titles
            await context.bot.send_message(chat_id=self.tg_thread_id, text=tg_chapter_overview, parse_mode='html')
            
            

        except Exception as e:
            print(f"Error while scaffolding sub-chapters: {e}\nExit to chat mode.\n")
        

    async def generate_content(self, update: Update, context: CallbackContext):
        self.process_status = "generate content"
        content = ""
        gen_doc = ""
        
        tg_parent_chapter_message = None
        tg_sub_chapter_message = None
        chevron = "   "
        
      
        try:
            for parent_chapter, sub_chapter_list in self.chapter_titles.items():
                gen_doc += "\n" + parent_chapter + "\n\n" # add empty line + parent chapter
                if not tg_parent_chapter_message:
                    tg_parent_chapter_message = await context.bot.send_message(chat_id=self.tg_thread_id, text=f"\n\nprocessing parent-chapter {parent_chapter}\n\n")
                else:
                    await context.bot.edit_message_text(chat_id=self.tg_thread_id, message_id=tg_parent_chapter_message.message_id, text=f"\n\nprocessing parent-chapter {parent_chapter}\n\n")
                    
                for sub_chapter in sub_chapter_list:
                    gen_doc += "\n" + sub_chapter + "\n" # add empty line + parent chapter
                    
                    prompt = f"""
                    Your role: You are a generative artificial intelligence. Your speciality is to generate academic essays and lectures.
                    Your task: You will be given a topic and a chapter title. Your task is to generate the text for the title in context of the title and the topic.
                    Knowledge: You will use your general knowledge that was given to you by your training. If there is a document attached, you will use this knowledge too and if not attached you will use your general knowledge.
                    Comments: You strictly adhere to deliver content only. You never comment your content or lack thereof. You will never mention that you don't know something and you will never apologize.
                    Content: You will create content only for sub-chapters. In case of parent chapters, you will just return the parent chapter title and you will refrain from adding further content.
                    Length: the content you create for sub-chapters should be at minimum 50 characters and a maximum of 100 characters in length.
                    Language: You will generate your response in {self.language} language.
                    Social responsibility: If the subject in question belongs to the public domain, for example a public figure or organisation, even if the topic may be perceived controversial, you will give a full response based on available data you gained from your training.
                    Style: Your audience is consisting of high-profile scholars and academics, therefore choose expressions and language style accordingly.
                    Purpose: The purpose of this task is to generate the content for the present sub-chapter.
                    Topic in context to each chapter: {self.instruction_text}
                    List of all chapters and sub-chapters belonging to this document for your reference: {self.all_chapter_titles}
                    In general context to the topic, generate the content expanding on the following subchapter title, without mentioning the title explicitly in the content you create: \"{sub_chapter}\"
                    """
                    message = OPENAI_CLIENT.beta.threads.messages.create(
                        thread_id=self.oai_docgen_thread_id,
                        role="user",
                        content=prompt
                    )
                    
                    run = OPENAI_CLIENT.beta.threads.runs.create(
                    thread_id=self.oai_docgen_thread_id,
                    assistant_id=self.assistant.id,
                    instructions=BC.OPENAI_INSTRUCTIONS
                    )
                    
                    counter = 0
                    while True:
                        counter += 1
                        
                        chevron = SharedUtils.shift_chevron(counter)
                            
                        # preparing chevron bold index
                        if not tg_sub_chapter_message: 
                            message_text = f"\n\nprocessing sub-chapter {sub_chapter[:25]}...{chevron}\n\n"
                            tg_sub_chapter_message = await context.bot.send_message(chat_id=self.tg_thread_id, text=message_text, parse_mode='markdown')
                        else:
                            updated_message_text = f"\n\nprocessing sub-chapter {sub_chapter[:25]}...{chevron}\n\n"
                            try:
                                await context.bot.edit_message_text(chat_id=self.tg_thread_id, message_id=tg_sub_chapter_message.message_id, text=updated_message_text, parse_mode='markdown')
                            except Exception as e:
                                counter += 1
                                chevron = SharedUtils.shift_chevron(counter)
                                print("Telegram refuses to update a message.")

                        await context.bot.send_chat_action(chat_id=self.tg_thread_id, action='typing')
                        run = OPENAI_CLIENT.beta.threads.runs.retrieve(
                            thread_id = self.oai_docgen_thread_id,
                            run_id = run.id
                        )
                        print(run.status) if BC.VERBOSE else None
                        if run.status == "completed":
                            break
                        await asyncio.sleep(3)
                    
                    messages = OPENAI_CLIENT.beta.threads.messages.list(
                        thread_id=self.oai_docgen_thread_id
                    )
                    # pick correct message
                    last_message = messages.data[0]
                    oai_response = last_message.content[0].text.value
                    oai_response = SharedUtils.remove_reference(oai_response=oai_response)
                    print(f"\n\n {sub_chapter}\n") if BC.VERBOSE else None
                    print(f"{oai_response}\n\n") if BC.VERBOSE else None
                    # sometimes the AI generates content including a leading sub-chapter title
                    # we don't want that as we add the sub-chapter title programmatically
                    if oai_response.startswith(sub_chapter):
                        # Replace the sub-title with an empty string
                        oai_response = oai_response[len(sub_chapter):]
                    gen_doc += oai_response + "\n" # generated content + empty line

            export_document = DocumentExport()
            export_document.create_word_doc("lecture.docx", gen_doc)
            await context.bot.send_document(
                chat_id=self.tg_thread_id,
                document=open("lecture.docx", 'rb'),
                filename="lecture.docx",
                caption="Here's your Word document!"
            )
            self.oai_docgen_thread = None  # hand over to garbage collection
            self.oai_docgen_thread_id = None # hand over to garbage collection
            chapter_titles = {} # reset dicionary and make it ready for the next job

            
        except Exception as e:
            print(f"Error while generating content: {e}\nExit to chat mode.\n")
        self.process_complete = True # setting completion flag to exit loop
        return content
        
        
    async def handle_user_input(self, update: Update, context: CallbackContext):
        user_input = update.message.text.lower()
        if self.process_status == "waiting for user input":
            if user_input == 'approve':
                self.process_status = "generate content"
            elif user_input == 'cancel':
                self.process_complete = True
        

    def is_complete(self):
        print(f"is_complete = {self.process_complete}")
        return self.process_complete
    
    def set_complete(self):
        self.process_complete = True
        self.process_status = "complete"
        print(f"set process status to {self.process_status}") if BC.VERBOSE else None


    async def execute(self, update: Update, context: CallbackContext, tg_user_message :str):
        
        if self.process_status == "generate main chapters":
            await self.generate_main_chapters(update, context)
            self.process_status = "generate sub chapters"
        
        if self.process_status == "generate sub chapters":
            await self.generate_sub_chapters(update, context)
            self.process_status = "review and approve"

        if self.process_status == "review and approve":
            context.user_data['review_main_chapters'] = True
            #Convert document types to a list o lists for ReplyKeyboardMarkup
            keyboard_options = (['approve'], ['cancel'])
            
            await context.bot.send_message(
                chat_id=update.message.chat_id,
                text = "<b>Please review main chapters and choose option on how to proceed.</b>",
                reply_markup=ReplyKeyboardMarkup(keyboard_options, one_time_keyboard=True),
                parse_mode='html'
            )
            self.process_status = "waiting for user choice"
            return
            
        if self.process_status == "waiting for user choice":
            if tg_user_message.lower() == "cancel":
                self.set_complete()
                print("process ended") if BC.VERBOSE else None
                return
            elif tg_user_message.lower() == "approve":
                self.process_status = "generate content"
            
        if self.process_status == "generate content":
            await self.generate_content(update, context)
            self.set_complete()
        
