import asyncio
import re
import sys
from openai import OpenAI, NotFoundError
from config import BOT_CONSTANTS as BC
from telegram import Update, ReplyKeyboardMarkup, KeyboardButton # new
from telegram.ext import filters, MessageHandler, ApplicationBuilder, CommandHandler, ContextTypes, CallbackContext # added InlineQueryhandler
from docx import Document


# Initialize OpenAI client
OPENAI_CLIENT = OpenAI(api_key=BC.OPENAI_API_KEY)


def create_word_doc(output_file, input_string):
    doc = Document()
    
    #Add each line to the Word document
    for line in input_string.split('\n'):
        doc.add_paragraph(line)
        
    # Save the Word document
    doc.save(output_file)


# just the start handler - not important
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await context.bot.send_message(chat_id=update.effective_chat.id, text=BC.TG_BOT_GREETING)


# instructions handler
# user decided to enter instructions. user_status flag is set to 'instructions'
# next user input will be handled by the echo function
async def handle_instructions(update: Update, context: CallbackContext) -> None:
    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Please enter your instructions:"
    )
    set_user_status(update.effective_chat.id, 'instructions')
    print("user_state: ", user_state)
    


# scaffold handler
# gives user the choice between 'enter instructions' or to 'cancel' the process
async def scaffold(update: Update, context: CallbackContext) -> None:
    user = update.effective_user
    await context.bot.send_message(
        chat_id=update.message.chat_id,
        # text=f"Hello {user.mention_html()}!",
        text = "Choose an option:",
        reply_markup=ReplyKeyboardMarkup([['enter instructions', 'cancel']], one_time_keyboard=True),
        parse_mode='html'
    )
    # text = 'You just entered the scaffold feature.'
    # await context.bot.send_message(chat_id=update.effective_chat.id, text=text)


def inline_process_string(query):
    # process the original user query the way you want
    # before it is submitted
    return query


async def create_scaffold(update: Update, context: ContextTypes.DEFAULT_TYPE, assistant):
    tg_thread_id = update.effective_chat.id
    print(f"scaffold tg_thread_id {tg_thread_id}")

    oai_thread_id = get_thread(tg_thread_id=tg_thread_id)
    instruction_text = update.message.text

    # existing chat thread or a new one (existing chat or new chat, create or get ids in mapper)
    if oai_thread_id is None:
        oai_thread = OPENAI_CLIENT.beta.threads.create()
        oai_thread_id = oai_thread.id
        add_thread(tg_thread_id=tg_thread_id, oai_thread_id=oai_thread_id)
        
    prompt = f"""
    Your role: You are a generative artificial intelligence. Your speciality is to generate the scaffold, respectively structure of a lecture.
    Your task: you will generate a structure of a lecture accordingly to the instructions given to you by the User-Instruction. The structure will consist of chapters and sub-chapters.
    You will return a list of at least 25 sub-chapters. Group sub-chapters by topic and create a parent chapter for each topic.
    Enumeration: enumerate parent chapters incrementally. For the subchapters use as a prefix the number of the parent chapter followed by a dot and as a suffix enumerate starting from 1.
    Format of your response: We want to iterate through your response, therefore return your response as an enumerated list where each chapter or sub-chapter is a record followed by a carriage-return character. 
    The purpose of this task: The scaffold (list of chapters) generated by you will be used as basis to generate the full text in an iterative process at a later time.
    User-Instruction: {instruction_text}
    """
    print(f"\n\nprompt:\n{prompt}\n\n")
    message = OPENAI_CLIENT.beta.threads.messages.create(
        thread_id=oai_thread_id,
        role="user",
        content=prompt
    )
    
    run = OPENAI_CLIENT.beta.threads.runs.create(
    thread_id=oai_thread_id,
    assistant_id=assistant.id,
    instructions=BC.OPENAI_INSTRUCTIONS
    )
    
    while True:
        await context.bot.send_chat_action(chat_id=tg_thread_id, action='typing')
        run = OPENAI_CLIENT.beta.threads.runs.retrieve(
            thread_id = oai_thread_id,
            run_id = run.id
        )
        print(run.status) if BC.VERBOSE else None
        if run.status == "completed":
            break
        await asyncio.sleep(5)
        
    # Remove the "processing request..." message

    messages = OPENAI_CLIENT.beta.threads.messages.list(
        thread_id=oai_thread_id
    )
    print(f"structure message: {messages}")
    # pick correct message
    last_message = messages.data[0]
    oai_response = last_message.content[0].text.value
    oai_response = remove_reference(oai_response=oai_response)
    
    print(f"\n\noai_response: {oai_response}\n\n\n")
    
    # Split the text into lines
    text = oai_response.split('\n')
    
    list_of_lines = []
    
    # Iterate through lines
    for line in text:
        if line.strip() == '':
            continue
        line = line.lstrip()
        print(line)
        if line.strip().startswith(('1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.', 
                                   '10.', '11.', '12.', '13.', '14.', '15.', '16.', '17.', 
                                   '18.', '19.', '20.', '20.', '21.', '22.', '23.', '24.',
                                   '25.', '26.', '27.', '28.', '29.', '30.')):
            list_of_lines.append(line)
        
    gen_doc = ""
    
    language = "English"
        
    for line in list_of_lines:
        prompt = f"""
        Your role: You are a generative artificial intelligence. Your speciality is to generate academic essays and lectures.
        Your task: You will be given a topic and a chapter title. Your task is to generate the text for the title in context of the title and the topic.
        Knowledge: You will use your general knowledge that was given to you by your training. If there is a document attached, you will use this knowledge too and if not attached you will use your general knowledge.
        Comments: You strictly adhere to deliver content only. You never comment your content or lack thereof. You will never mention that you don't know something and you will never apologize.
        Content: You will create content only for sub-chapters. In case of parent chapters, you will just return the parent chapter title and you will refrain from adding further content.
        Length: the content you create for sub-chapters should be at minimum 800 Bytes and a maximum of 2 kilobyte in length.
        Language: You will generate your response in {language} language.
        Style: Your audience is consisting of high-profile scholars and academics, therefore choose expressions and language style accordingly.
        Purpose: The purpose of this task is to generate the content for the present sub-chapter.
        Topic: {instruction_text}
        Chapter title: {line}
        """
        message = OPENAI_CLIENT.beta.threads.messages.create(
            thread_id=oai_thread_id,
            role="user",
            content=prompt
        )
        
        run = OPENAI_CLIENT.beta.threads.runs.create(
        thread_id=oai_thread_id,
        assistant_id=assistant.id,
        instructions=BC.OPENAI_INSTRUCTIONS
        )
        
        while True:
            await context.bot.send_chat_action(chat_id=tg_thread_id, action='typing')
            run = OPENAI_CLIENT.beta.threads.runs.retrieve(
                thread_id = oai_thread_id,
                run_id = run.id
            )
            print(run.status) if BC.VERBOSE else None
            if run.status == "completed":
                break
            await asyncio.sleep(5)
        
        messages = OPENAI_CLIENT.beta.threads.messages.list(
            thread_id=oai_thread_id
        )
        # pick correct message
        last_message = messages.data[0]
        oai_response = last_message.content[0].text.value
        oai_response = remove_reference(oai_response=oai_response)
        print(f"\n\n {line}\n")
        print(f"{oai_response}\n\n\n")
        gen_doc += "\n\n" + oai_response
    
    create_word_doc("lecture.docx", gen_doc)
    await context.bot.send_document(
        chat_id=tg_thread_id,
        document=open("lecture.docx", 'rb'),
        filename="lecture.docx",
        caption="Here's your Word document!"
    )
    
    # # Update telegram chat with the assistant's reponse
    # sent_message = await context.bot.send_message(chat_id=tg_thread_id, text=oai_response)
    # sent_message_id = sent_message.message_id
    # add_msg_id(sent_message_id)
    

# the echo function receives the user input from TG, sends it to the OAI assistant, 
# retrieves the result, and sends it back to TG
async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE, assistant):
    tg_thread_id = update.effective_chat.id
    print(f'tg_thread_id {tg_thread_id}')
    if get_user_status(tg_thread_id) == "instructions":
        print("OK - now we will create the scaffold for the topic")
        await create_scaffold(update, context, assistant)
        return
        
    if not update.edited_message:
        tg_message_text = update.message.text
    else:
        print("Editing of message not yet supported") if BC.VERBOSE else None
        return
    
    chat = await context.bot.get_chat(tg_thread_id) # get the chat
    chat_type = chat.type
    
    chat_title = chat.title if chat.title else "Private Chat"
    
    if not update.message.reply_to_message:
    
        if chat_type == 'private':
            print(f"Received a message in a private chat with user ID: {tg_thread_id}") if BC.VERBOSE else None
        elif chat_type in ['group', 'supergroup']:
            print(f"Received a message in a group '{chat_title}' with ID: {tg_thread_id}") if BC.VERBOSE else None
        elif chat_type == 'channel':
            print(f"Received a message in a channel '{chat_title}' with ID: {tg_thread_id}") if BC.VERBOSE else None
        else:
            print(f"Receive a message in an unknown chat type with ID: {tg_thread_id}") if BC.VERBOSE else None

            
        if chat_type in ['group', 'supergroup', 'channel'] and not any(call_sign.lower() in tg_message_text.lower() for call_sign in BC.TG_BOT_CALLSIGNS):
            print('message not addressed to the bot') if BC.VERBOSE else None
            return
        
    elif not is_bot_msg(update.message.reply_to_message.id):
        print('reply to message is not addressed at bot') if BC.VERBOSE else None
        return
        
    try:
        oai_thread_id = get_thread(tg_thread_id=tg_thread_id)

        # existing chat thread or a new one (existing chat or new chat, create or get ids in mapper)
        if oai_thread_id is None:
            oai_thread = OPENAI_CLIENT.beta.threads.create()
            oai_thread_id = oai_thread.id
            add_thread(tg_thread_id=tg_thread_id, oai_thread_id=oai_thread_id)

        message = OPENAI_CLIENT.beta.threads.messages.create(
            thread_id=oai_thread_id,
            role="user",
            content=tg_message_text
        )
        
        run = OPENAI_CLIENT.beta.threads.runs.create(
        thread_id=oai_thread_id,
        assistant_id=assistant.id,
        instructions=BC.OPENAI_INSTRUCTIONS
        )
        
        while True:
            await context.bot.send_chat_action(chat_id=tg_thread_id, action='typing')
            run = OPENAI_CLIENT.beta.threads.runs.retrieve(
                thread_id = oai_thread_id,
                run_id = run.id
            )
            print(run.status) if BC.VERBOSE else None
            if run.status == "completed":
                break
            await asyncio.sleep(5)
            
        # Remove the "processing request..." message

        messages = OPENAI_CLIENT.beta.threads.messages.list(
            thread_id=oai_thread_id
        )
        
        # pick correct message
        last_message = messages.data[0]
        oai_response = last_message.content[0].text.value
        oai_response = remove_reference(oai_response=oai_response)
        
        # Update telegram chat with the assistant's reponse
        sent_message = await context.bot.send_message(chat_id=tg_thread_id, text=oai_response)
        sent_message_id = sent_message.message_id
        add_msg_id(sent_message_id)
        
    except Exception as e:
        error_message = BC.OPENAI_ERROR_MSG
        await context.bot.send_message(chat_id=tg_thread_id, text=error_message)
        print(f"Error in processing user request: {e}")


# set user status
def set_user_status(user_id, state) -> None:
    user_state[user_id] = state

# get user status
def get_user_status(user_id) -> str:
    try:
        return user_state[user_id]
    except KeyError as e:
        print(f"unknown key, {e}")
        return ''


# add bot-message id to list
def add_msg_id(msg_id) -> None:
    bot_msg_id_list.append(msg_id)
    
    if len(bot_msg_id_list) > BC.TG_MAX_MESSAGES: #limit max. length of list
        bot_msg_id_list.pop(0)

# check if the replied_to message originally was a message from the bot
def is_bot_msg(replied_to_msg_id) -> bool:
    if replied_to_msg_id in bot_msg_id_list:
        return True
    else:
        return False

# add thread into the mapper
def add_thread(tg_thread_id, oai_thread_id) -> None:
    if tg_thread_id not in oai_tg_id_mapper:
        oai_tg_id_mapper[tg_thread_id] = oai_thread_id
    
    if len(oai_tg_id_mapper) > BC.TG_MAX_THREADS: # limit max. length of dict
        oai_tg_id_mapper.popitem(last=False) 


# get thread from the mapper
def get_thread(tg_thread_id) -> str:
    if tg_thread_id in oai_tg_id_mapper:
        return oai_tg_id_mapper[tg_thread_id]


def remove_reference(oai_response) -> str:
    # Regex pattern
    pattern = re.compile(r'【.*】')
    clean_text = re.sub(pattern, '', oai_response)
    return clean_text


if __name__ == '__main__':
    print("bot initializing...")
    oai_tg_id_mapper = {}
    bot_msg_id_list = []
    user_state = {}
    
    # try:
    #     file = OPENAI_CLIENT.files.retrieve(file_id=BC.OPENAI_FILE_ID)
    # except NotFoundError as e:
    #     print(f"File not found error: {e}")
    #     print(f"bot server terminated - the file id is probably wrong")
    #     sys.exit()
    # except Exception as e:
    #     print(f"Some general error just happened: {e}")
    #     sys.exit()
    
    try:
        assistant = OPENAI_CLIENT.beta.assistants.retrieve(BC.OPENAI_ASSISTANT_ID)
    except NotFoundError as e:
        print(f"Assistant not found error? {e}")
        print(f"bot server terminated - the assistant id is probably wrong")
        sys.exit()
    
    application = ApplicationBuilder().token(BC.TG_BOT_TOKEN).build()

    start_handler = CommandHandler('start', start)
    scaffold_handler = CommandHandler('scaffold', scaffold) 
    echo_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), lambda update, context: echo(update, context, assistant))
    instructions_handler = (MessageHandler(filters.Regex(r'^enter instructions$'), handle_instructions))

    application.add_handler(start_handler)
    application.add_handler(scaffold_handler)
    application.add_handler(instructions_handler)
    application.add_handler(echo_handler)
    print("Bot is now ready.")
    application.run_polling()
